name: Check source code styling

on:
  push:
    paths:
      - '**/*.cs'
      - '.github/workflows/lint.yml'
  repository_dispatch:
  workflow_dispatch:

jobs:
  test:
    name: Check code styling
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.101
      - name: Setup dotnet-format
        run: dotnet tool install -g dotnet-format --version 5.1.250801
      - name: Run format checker
        run: dotnet format --verify-no-changes --verbosity detailed
