name: Publish maimaiDX common utils

on:
  push:
    paths:
      - 'Pepper.Commons.Maimai/**'
      - 'Pepper.Commons/**'
      - '.github/workflows/maimai-commons-nuget-publish.yml'
    branches:
      - master
  repository_dispatch:
  workflow_dispatch:

jobs:
  publish:
    name: Publish to feed
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.101
      - name: Package
        run: |
          dotnet build
          NUGET_ENABLE_LEGACY_CSPROJ_PACK=true nuget pack Pepper.Commons.Maimai -OutputDirectory dist/ -Suffix "$(date +%Y%m%d-%H%M)" -IncludeReferencedProjects;
      - name: Publish to GitHub
        env:
          API_KEY: ${{ secrets.GITHUB_TOKEN }}
        run: |
          dotnet nuget push dist/*.nupkg --api-key "$API_KEY" --source "https://nuget.pkg.github.com/$GITHUB_ACTOR/index.json";