name: Run test

on:
  push:
    paths:
    - 'Pepper/**'
    - '.github/workflows/test.yml'
    - 'Pepper.Test/**'
  repository_dispatch:
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04
    strategy:
      matrix: 
        filters: ['AllCommandsFullyDescribed']
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Test
      run: dotnet test Pepper.Test --filter ${{ matrix.filters }}
