name: Run fuzzy search tests

on:
  push:
    paths:
      - 'Pepper.FuzzySearch/**'
      - '.github/workflows/test-fuzzy.yml'
      - 'Pepper.FuzzySearch.Test/**'
  repository_dispatch:
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Test
        run: dotnet test Pepper.FuzzySearch.Test
