name: Run maimaiDX frontend tests

on:
  push:
    paths:
      - 'Pepper.Commons/**/*.cs'
      - 'Pepper.Commons/**/*.csproj'
      - 'Pepper.Commons.Maimai/**/*.cs'
      - 'Pepper.Commons.Maimai/**/*.csproj'
      - 'Pepper.Frontends.Maimai/**/*.cs'
      - 'Pepper.Frontends.Maimai/**/*.csproj'
      - 'boomer.sln'
      - 'nuget.config'
      - '.github/workflows/test-maimai.yml'
  repository_dispatch:
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.101
      - name: Setup
        env:
          SQL_PATH: ${{ secrets.MAIMAI_DATA_SQL }} 
        run: |
          sudo systemctl start mysql.service;
          mysql -u root -proot -e "create database maimai";
          curl -L $SQL_PATH | mysql -u root -proot maimai;
      - name: Test
        env:
          MARIADB_CONNECTION_STRING_MAIMAI: Server=localhost;Port=3306;User=root;Password=root;Database=maimai
        run: dotnet test Pepper.Frontends.Maimai.Test
