name: Run test

on:
  push:
    paths:
    - 'Pepper/**'
    - '.github/workflows/test.yml'
    - 'Pepper.Test/**'
  repository_dispatch:
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.101
    - name: Test
      run: dotnet test Pepper.Test
